[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "buttonless"

opacity = 0.85
blur = true

option_as_alt = "OnlyRight"

[font]
normal.family = "MesloLGS NF"
size = 12
